# Configuration for the Conveyor CI Server.
# Copy this file to 'config.yml' or remove example from the name of file; and fill in your secrets.
# Please ignore current "TODO" comments, they are for us.

# TODO: Add later support for other types of databases, like PostgresSQL

server:
  # The port the web server will listen on.
  port: "8080"

  # The path to the SQLite database file.
  database: "conveyor.db"

security:
  # A long, random, secret key for securing user sessions.
  # You can generate one with: openssl rand -hex 32
  session_key: "change-this-to-a-long-random-string"

  # TODO: Add GitLab and more Git platforms in future
  # The secret you configured in your GitHub webhook settings.
  github_webhook_secret: "change-this-to-your-github-webhook-secret"