# Use the official Go image with Alpine Linux
FROM golang:1.25-alpine AS builder
WORKDIR /app
RUN apk add --no-cache gcc musl-dev git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w -extldflags=-static" -o /conveyor-agent ./cmd/conveyor-agent

###

FROM alpine:latest
RUN addgroup -S conveyor && adduser -S conveyor -G conveyor

USER conveyor
WORKDIR /home/conveyor/

COPY --from=builder /conveyor-agent .
ENTRYPOINT ["./conveyor-agent"]